import type { NextPage } from 'next'
import Head from 'next/head'
import { BodyContent } from './components/body'
import { HeadCard, Navber } from './components/haed'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeadCard />
        <Navber />
      </div>
      <div className='mt-10'>
        <BodyContent />
      </div>
      <br />
    </div>
  )
}

export default Home
